### ISSUE TITLE
Issue runningn npm run css

### ISSUE THREAD

**Issue by donundeen** [reelyactive/web-style-guide#1]
Error: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_maps.scss 55:16  @import
  scss/bootstrappyactive.scss 22:9              root stylesheet
ERROR: "css-compile" exited with 65.

Solution show here:
https://stackoverflow.com/questions/75873195/getting-primary-primary-text-emphasis-dark-error-while-converting-scss-to-cs 
@import "_variables-dark.scss" before @import "_map.scss" will work.

added around line 22 of bootstrappyactive.css:
// 3. Remainder of required Bootstrap stylesheets
@import "../node_modules/bootstrap/scss/variables";
@import "../node_modules/bootstrap/scss/variables-dark";
@import "../node_modules/bootstrap/scss/maps";

**Comment by jeffyactive** [comment]
Thanks for the heads up @donundeen, the web-style-guide has been updated as follows:

- release-1.2 is now capped at Bootstrap v5.2 to avoid the error you described
- release-1.3 was added which adopts Bootstrap v5.3 and the "dark mode" features
- release-1.3 was merged into the master branch

Moving forward, the Bootstrap version is specified using "~" rather than "^" as this isn't the first time that breaking changes have been introduced in a minor Bootstrap version update.
